### ISSUE TITLE
Django 3.0 Staticfiles

### ISSUE THREAD

**Issue by BenjaminPalko** [agusmakmun/django-markdown-editor#106]
When trying to start a Django application running on version **3.0**, with martor **1.4.4** this error occurs:
```
Internal Server Error: /martor/markdownify/
Traceback (most recent call last):
  File "F:\Benja\Development\PycharmProjects\website\venv\lib\site-packages\martor\utils.py", line 29, in markdownify
    return markdown.markdown(
  File "F:\Benja\Development\PycharmProjects\website\venv\lib\site-packages\markdown\core.py", line 390, in markdown
    md = Markdown(**kwargs)
  File "F:\Benja\Development\PycharmProjects\website\venv\lib\site-packages\markdown\core.py", line 99, in __init__
    self.registerExtensions(extensions=kwargs.get('extensions', []),
  File "F:\Benja\Development\PycharmProjects\website\venv\lib\site-packages\markdown\core.py", line 126, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "F:\Benja\Development\PycharmProjects\website\venv\lib\site-packages\markdown\core.py", line 166, in build_extension
    module = importlib.import_module(ext_name)
  File "C:\Users\Benja\AppData\Local\Programs\Python\Python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\Benja\Development\PycharmProjects\website\venv\lib\site-packages\martor\extensions\emoji.py", line 5, in <module>
    from django.contrib.staticfiles.templatetags.staticfiles import static
ModuleNotFoundError: No module named 'django.contrib.staticfiles.templatetags'
```

It looks like there is a file `emoji.py` that is trying to import from Django:
```
from django.contrib.staticfiles.templatetags.staticfiles import static
```

Looking at the Django 3.0 [release notes](https://docs.djangoproject.com/en/3.0/releases/3.0/#features-removed-in-3-0) it seems they removed the *staticfiles* template tag library, a solution to this issue might be to switch over to the *static* template tag library.

**Comment by koenw** [comment]
Yeah, you're right, I noticed the same. I've "fixed" this in #102 (probably in a non-backward compatible way) , but the author does not seem to be active at the moment. See also #101.
