### ISSUE TITLE
safe_markdown template tag isn't safe

### ISSUE THREAD

**Issue by apoorvaeternity** [agusmakmun/django-markdown-editor#130]
The `safe_markdown` template tag isn't safe and can cause `XSS` vulnerabilities
see: https://python-markdown.github.io/change_log/release-3.0/#safe_mode-and-html_replacement_text-keywords-deprecated

**Comment by macieyn** [comment]
Hi @agusmakmun. 
I'm getting this error 
```
VersionNotCompatible at / The markdown isn't compatible, please reinstall your python markdown into Markdown>=3.0
```

Which is odd because: 
```bash
$ pip freeze | grep Markdown
Markdown==3.0
```
I believe it's related to this issue, because when I comment out `'martor.extensions.escape_html'` in settings, page loads almost as it should. Almost, means code snippet is not in color, while in admin preview everything looks as expected. 

Full traceback: 
```python
Environment:

Request Method: GET
Request URL: http://localhost:8000/

Django Version: 3.1
Python Version: 3.8.5
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'martor',
 'posts']

Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']


Template error:
In template /app/templates/base.html, error at line 0
   The markdown isn't compatible, please reinstall your python markdown into Markdown>=3.0
   1 : {% load static %}
   2 : <!DOCTYPE html>
   3 : <html lang="en">
   4 : <head>
   5 :     <meta charset="UTF-8">
   6 :     <meta name="viewport" content="width=800px, initial-scale=1.0">
   7 :     <title>Document</title>
   8 : 
   9 :      <link href="{% static 'plugins/css/ace.min.css' %}" type="text/css" media="all" rel="stylesheet" />
   10 :   <link href="{% static 'plugins/css/semantic.min.css' %}" type="text/css" media="all" rel="stylesheet" />


Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/martor/utils.py", line 29, in markdownify
    return markdown.markdown(
  File "/usr/local/lib/python3.8/site-packages/markdown/core.py", line 390, in markdown
    md = Markdown(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/markdown/core.py", line 99, in __init__
    self.registerExtensions(extensions=kwargs.get('extensions', []),
  File "/usr/local/lib/python3.8/site-packages/markdown/core.py", line 126, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/usr/local/lib/python3.8/site-packages/markdown/core.py", line 166, in build_extension
    module = importlib.import_module(ext_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    <source code not available>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    <source code not available>
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
    <source code not available>

During handling of the above exception (No module named 'martor.extensions.escape_html'), another exception occurred:
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/posts/views.py", line 9, in home
    return render(request, 'posts/home_page.html', context={'posts': posts})
  File "/usr/local/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 988, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 698, in resolve
    new_obj = func(obj, *arg_vals)
  File "/usr/local/lib/python3.8/site-packages/martor/templatetags/martortags.py", line 21, in safe_markdown
    return mark_safe(markdownify(field_name))
  File "/usr/local/lib/python3.8/site-packages/martor/utils.py", line 36, in markdownify
    raise VersionNotCompatible("The markdown isn't compatible, please reinstall "

Exception Type: VersionNotCompatible at /
Exception Value: The markdown isn't compatible, please reinstall your python markdown into Markdown>=3.0
```

Project is running in docker, Django is installed in `python:3.8-slim-buster` image.

Let me know if you need more details.

**Comment by agusmakmun** [comment]
@macieyn what happend when you remove the `'martor.extensions.escape_html'` from `MARTOR_MARKDOWN_EXTENSIONS`?

to this;

```python
MARTOR_MARKDOWN_EXTENSIONS = [
    'markdown.extensions.extra',
    'markdown.extensions.nl2br',
    'markdown.extensions.smarty',
    'markdown.extensions.fenced_code',

    # Custom markdown extensions.
    'martor.extensions.urlize',
    'martor.extensions.del_ins',      # ~~strikethrough~~ and ++underscores++
    'martor.extensions.mention',      # to parse markdown mention
    'martor.extensions.emoji',        # to parse markdown emoji
    'martor.extensions.mdx_video',    # to parse embed/iframe video
]
```

**Comment by macieyn** [comment]
Lik I said previously:
> when I comment out 'martor.extensions.escape_html' in settings, page loads almost as it should.

So my code looks like this: 
```python
MARTOR_MARKDOWN_EXTENSIONS = [
    'markdown.extensions.extra',
    'markdown.extensions.nl2br',
    'markdown.extensions.smarty',
    'markdown.extensions.fenced_code',

    # Custom markdown extensions.
    'martor.extensions.urlize',
    'martor.extensions.del_ins',      # ~~strikethrough~~ and ++underscores++
    'martor.extensions.mention',      # to parse markdown mention
    'martor.extensions.emoji',        # to parse markdown emoji
    'martor.extensions.mdx_video',    # to parse embed/iframe video
    # 'martor.extensions.escape_html' 
]
```
With settings like this it does work, no errors.
But I have no knowledge about vulneralibities, so I can't test it against.

### After some time
It turns out, that this fix is not reflected in pip package, whereas your readme file in settings chapter includes it ⏪ explains my issue.

**Comment by agusmakmun** [comment]
@macieydev did your problem are ralated with this issue?
https://github.com/agusmakmun/django-markdown-editor/issues/167

please check it out.
