### ISSUE TITLE
utils.markdownify --- TypeError: cannot serialize b'Contents'

### ISSUE THREAD

**Issue by neigrok** [agusmakmun/django-markdown-editor#28]
Hello! Look at that, code from the docstring of markdownify. I cant get what's wrong

```
>>> from martor.utils import markdownify
>>> content = "![awesome](http://i.imgur.com/hvguiSn.jpg)"
>>> markdownify(content)
```

```
Traceback (most recent call last):
  File "/home/vsyrov/Home/PycharmProjects/web-linux36/lib/python3.5/site-packages/markdown/serializers.py", line 95, in _escape_cdata
    if "&" in text:
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/vsyrov/Home/PycharmProjects/web-linux36/lib/python3.5/site-packages/martor/utils.py", line 28, in markdownify
    extension_configs=MARTOR_MARKDOWN_EXTENSION_CONFIGS
  File "/home/vsyrov/Home/PycharmProjects/web-linux36/lib/python3.5/site-packages/markdown/__init__.py", line 494, in markdown
    return md.convert(text)
  File "/home/vsyrov/Home/PycharmProjects/web-linux36/lib/python3.5/site-packages/markdown/__init__.py", line 375, in convert
    newRoot = treeprocessor.run(root)
  File "/home/vsyrov/Home/PycharmProjects/web-linux36/lib/python3.5/site-packages/markdown/extensions/toc.py", line 260, in run
    toc = self.markdown.serializer(div)
  File "/home/vsyrov/Home/PycharmProjects/web-linux36/lib/python3.5/site-packages/markdown/serializers.py", line 282, in to_xhtml_string
    return _write_html(ElementTree(element).getroot(), format="xhtml")
  File "/home/vsyrov/Home/PycharmProjects/web-linux36/lib/python3.5/site-packages/markdown/serializers.py", line 203, in _write_html
    _serialize_html(write, root, qnames, namespaces, format)
  File "/home/vsyrov/Home/PycharmProjects/web-linux36/lib/python3.5/site-packages/markdown/serializers.py", line 188, in _serialize_html
    _serialize_html(write, e, qnames, None, format)
  File "/home/vsyrov/Home/PycharmProjects/web-linux36/lib/python3.5/site-packages/markdown/serializers.py", line 186, in _serialize_html
    write(_escape_cdata(text))
  File "/home/vsyrov/Home/PycharmProjects/web-linux36/lib/python3.5/site-packages/markdown/serializers.py", line 103, in _escape_cdata
    _raise_serialization_error(text)
  File "/home/vsyrov/Home/PycharmProjects/web-linux36/lib/python3.5/site-packages/markdown/serializers.py", line 78, in _raise_serialization_error
    "cannot serialize %r (type %s)" % (text, type(text).__name__)
TypeError: cannot serialize b'Contents' (type bytes)
>>> markdownify(content.encode('utf-8'))
Traceback (most recent call last):
  File "/home/vsyrov/Home/PycharmProjects/web-linux36/lib/python3.5/site-packages/markdown/serializers.py", line 95, in _escape_cdata
    if "&" in text:
TypeError: a bytes-like object is required, not 'str'
```

python 3.5.4

**Comment by neigrok** [comment]
I figured out, that exception raises in one of martor exceptions, some of them are custom. Problem in my code
