### ISSUE TITLE
Martor crashes with Markdown 3

### ISSUE THREAD

**Issue by lubo** [agusmakmun/django-markdown-editor#49]
Log:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/usr/local/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/defaulttags.py", line 517, in render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 993, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 703, in resolve
    new_obj = func(obj, *arg_vals)
  File "/usr/local/lib/python3.6/site-packages/martor/templatetags/martortags.py", line 21, in safe_markdown
    return mark_safe(markdownify(field_name))
  File "/usr/local/lib/python3.6/site-packages/martor/utils.py", line 28, in markdownify
    extension_configs=MARTOR_MARKDOWN_EXTENSION_CONFIGS
  File "/usr/local/lib/python3.6/site-packages/markdown/core.py", line 390, in markdown
    md = Markdown(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/markdown/core.py", line 100, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/usr/local/lib/python3.6/site-packages/markdown/core.py", line 126, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/usr/local/lib/python3.6/site-packages/markdown/core.py", line 181, in build_extension
    return module.makeExtension(**configs)
  File "/usr/local/lib/python3.6/site-packages/martor/extensions/del_ins.py", line 48, in makeExtension
    return DelInsExtension(configs=dict(configs))
  File "/usr/local/lib/python3.6/site-packages/markdown/extensions/__init__.py", line 42, in __init__
    self.setConfigs(kwargs)
  File "/usr/local/lib/python3.6/site-packages/markdown/extensions/__init__.py", line 73, in setConfigs
    self.setConfig(key, value)
  File "/usr/local/lib/python3.6/site-packages/markdown/extensions/__init__.py", line 61, in setConfig
    if isinstance(self.config[key][0], bool):
KeyError: 'configs'
```

Downgrading to Markdown 2.6.11 fixed the problem for me.

**Comment by kornikopic** [comment]
Same problem here

**Comment by yahyaalbashar** [comment]
what is the solution for this??

**Comment by kornikopic** [comment]
> what is the solution for this??

@lubo gave a temporary solution : 

> Downgrading to Markdown 2.6.11 fixed the problem for me.

**Comment by mr-ant** [comment]
Hi,
this problem is not really fixed.should downgrade to markdown 2.6 in requirements.txt. because now we'll get `VersionNotCompatible` error.
see below:
  File "/usr/local/lib/python3.6/site-packages/martor/templatetags/martortags.py", line 21, in safe_markdown
    return mark_safe(markdownify(field_name))
  File "/usr/local/lib/python3.6/site-packages/martor/utils.py", line 36, in markdownify
    raise VersionNotCompatible("The markdown isn't compatible, please reinstall "
martor.utils.VersionNotCompatible: The markdown isn't compatible, please reinstall your python markdown into Markdown==2.6.9

**Comment by baddev** [comment]
I ran into that with Markdown 3.1 and martor 1.4.0 :

    try:
        return markdown.markdown(
            str(markdown_content),
            safe_mode=MARTOR_MARKDOWN_SAFE_MODE,
            extensions=MARTOR_MARKDOWN_EXTENSIONS,
            extension_configs=MARTOR_MARKDOWN_EXTENSION_CONFIGS
        )
    except Exception as e:
        raise VersionNotCompatible("The markdown isn't compatible, please reinstall "
                                   "your python markdown into Markdown>=3.0")
in utils.py line 36, seems to do the trick.

**Comment by mintyPT** [comment]
This was closed? I'm currently seeing the issue

**Comment by stephane98** [comment]
Hello, this issue already exists. How can I fix it?

**Comment by 0p3r4t0r** [comment]
The error is not actually being caused by markdown. It is being caused by an outdated import request. The pull request above solves the problem and for details you can see issue #95. Cheers!
